# ME 793 Assignment 2: PCA
Moitreyee Sarkar- 18D170020


In [ ]:
#import libraries

import numpy as np
import pandas as pd
from scipy import linalg

In [ ]:
#mounting drive

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#read excel data file

db = pd.read_excel('/content/drive/MyDrive/data_PCA.xlsx')      
db

length  width  thickness
0       7      4          3
1       4      1          8
2       6      3          5
3       8      6          1
4       8      5          7
5       7      2          9
6       5      3          3
7       9      5          8
8       7      4          5
9       8      2          2

In [ ]:
#transform data to array

X=db.values              
X

array([[7, 4, 3],
       [4, 1, 8],
       [6, 3, 5],
       [8, 6, 1],
       [8, 5, 7],
       [7, 2, 9],
       [5, 3, 3],
       [9, 5, 8],
       [7, 4, 5],
       [8, 2, 2]])

### (a) Write a function for determining PCs of the above dataset X. Standardize your data i.e. use zero mean and normalized data using the ”Standardize” function shown in Tutorial.

In [ ]:
def standardize(a):                     #a here is the input data
    mean = sum(a)/len(a)                #computing mean
    var = sum((a-mean)**2)/len(a)       #computing variance
    snd = (a-mean)/(var**0.5)           #compute zero mean for normalizating data
    return snd                          #return snd i.e. Standard Normalized data

In [ ]:
#scaling the data using zero mean

X_scaled= standardize(X)         
X_scaled

array([[ 0.06917145,  0.33333333, -0.78867155],
       [-2.00597195, -1.66666667,  1.08911786],
       [-0.62254302, -0.33333333, -0.03755579],
       [ 0.76088591,  1.66666667, -1.53978732],
       [ 0.76088591,  1.        ,  0.71355998],
       [ 0.06917145, -1.        ,  1.46467574],
       [-1.31425748, -0.33333333, -0.78867155],
       [ 1.45260037,  1.        ,  1.08911786],
       [ 0.06917145,  0.33333333, -0.03755579],
       [ 0.76088591, -1.        , -1.16422944]])

### (b) Show the principal vectors i.e. matrix P.


In [ ]:
#getting the shape of the scaled matrix

n, m = X_scaled.shape                
X_scaled.shape    

(10, 3)

In [ ]:
#Computing the covariance matrix

cov_X = np.dot(X_scaled.T,  X_scaled ) / (n-1)      
cov_X

array([[ 1.11111111,  0.74295257, -0.11257082],
       [ 0.74295257,  1.11111111, -0.31991968],
       [-0.11257082, -0.31991968,  1.11111111]])

In [ ]:
eigen_values, eigen_vectors = np.linalg.eig(cov_X)         #computing eigen values and vectors
print("eigen values", eigen_values)                        #unsorted eigen values
print("eigen vectors", eigen_vectors)                      #unsorted eigen vectors

eigen values [1.9653046  0.33794439 1.03008435]
eigen vectors [[-0.64200458 -0.66321742  0.38467229]
 [-0.68636164  0.72074503  0.09713033]
 [ 0.34166917  0.20166619  0.91792861]]


In [ ]:
idx = eigen_values.argsort()[::-1]   
eigenValues = eigen_values[idx]
eigenVectors = eigen_vectors[:,idx]
print("sorted eigen values", eigenValues)                #unsorted eigen values
print("sorted eigen vectors", eigenVectors)              #unsorted eigen vectors

sorted eigen values [1.9653046  1.03008435 0.33794439]
sorted eigen vectors [[-0.64200458  0.38467229 -0.66321742]
 [-0.68636164  0.09713033  0.72074503]
 [ 0.34166917  0.91792861  0.20166619]]


In [ ]:
print("Principal vectors", eigenVectors.T)          #displaying principal vectors 

Principal vectors [[-0.64200458 -0.68636164  0.34166917]
 [ 0.38467229  0.09713033  0.91792861]
 [-0.66321742  0.72074503  0.20166619]]



### (c) Show the transformed data Y .


In [ ]:
#transformed data

Y = np.dot(X_scaled, eigenVectors)        
Y

array([[-0.54266035, -0.66495907,  0.03532425],
       [ 2.80389723,  0.06620673,  0.34879208],
       [ 0.61563102, -0.30632536,  0.1650593 ],
       [-2.15852616, -0.95883922,  0.38608588],
       [-0.93105243,  1.04481917,  0.36001316],
       [ 1.1423878 ,  1.27394577, -0.47124516],
       [ 0.80308178, -1.2618794 ,  0.47234173],
       [-1.24681973,  1.65563789, -0.0230066 ],
       [-0.28602725,  0.02451158,  0.1867989 ],
       [-0.1999119 , -0.87311811, -1.46016354]])

In [ ]:
pc1 = X_scaled.dot(eigenVectors.T[0])
pc2 = X_scaled.dot(eigenVectors.T[1])
pc3 = X_scaled.dot(eigenVectors.T[2])

res = pd.DataFrame(pc1, columns=["PC1"])      #creating pandas dataframe for better visualisation 
res["PC2"] = pc2
res["PC3"] = pc3

res               #all 3 principal components 

PC1       PC2       PC3
0 -0.542660 -0.664959  0.035324
1  2.803897  0.066207  0.348792
2  0.615631 -0.306325  0.165059
3 -2.158526 -0.958839  0.386086
4 -0.931052  1.044819  0.360013
5  1.142388  1.273946 -0.471245
6  0.803082 -1.261879  0.472342
7 -1.246820  1.655638 -0.023007
8 -0.286027  0.024512  0.186799
9 -0.199912 -0.873118 -1.460164

### (d) Determine the variances along the principal directions.

In [ ]:
var_principal = []
for i in range(len(eigenValues)):
    var_principal.append(eigenValues[i] / np.sum(eigen_values))
 
print(var_principal)     #varinaces along the principal directions

[0.5895913787011413, 0.3090253056329647, 0.10138331566589397]


### (e) Determine the principal axes using Scikit learn and compare with your solution. Does your solution compare well with that from the python library functions ? Why or why not ?


In [ ]:
from sklearn.decomposition import PCA    #import scikit pca library

In [ ]:
pca = PCA(n_components=3)     

In [ ]:
pca.fit_transform(X_scaled)      #Fit the model with X and applying transformation on X.

array([[-0.54266035, -0.66495907, -0.03532425],
       [ 2.80389723,  0.06620673, -0.34879208],
       [ 0.61563102, -0.30632536, -0.1650593 ],
       [-2.15852616, -0.95883922, -0.38608588],
       [-0.93105243,  1.04481917, -0.36001316],
       [ 1.1423878 ,  1.27394577,  0.47124516],
       [ 0.80308178, -1.2618794 , -0.47234173],
       [-1.24681973,  1.65563789,  0.0230066 ],
       [-0.28602725,  0.02451158, -0.1867989 ],
       [-0.1999119 , -0.87311811,  1.46016354]])

In [ ]:
pca.components_                #one eigenvector for each principal component

array([[-0.64200458, -0.68636164,  0.34166917],
       [ 0.38467229,  0.09713033,  0.91792861],
       [ 0.66321742, -0.72074503, -0.20166619]])

In [ ]:
pca.explained_variance_ratio_       #varinaces along the principal directions

array([0.58959138, 0.30902531, 0.10138332])

Principal axes using scikit was different from my solution (computing eigen vectors of covariance matrix of normalized data). Sign of one of the eigenvectors was opposite, although this should not be a problem as we do not need axes directions while considering principal components. After processing the input data with pca, principal components are the vectors that identify these axes. As a result, regardless of the direction each component is pointing, our data will be plotted on the same new axes.

---



### (f) Determine the principal axes using numpy and compare with your solution. Does your solution compare well with that from the python library functions ? Why or why not ?

In [ ]:
U, S, Vt = np.linalg.svd(X_scaled, full_matrices=True)
print ("Shape of U:" , U.shape, "   S:" , S.shape, "   Vt", Vt.shape)
print("U:", U)
print("S used for building Sigma:")
print(S)

Sigma = np.diag(S)         #creating singular value matrix
print("Sigma:")
print(Sigma)
print("V already transposed:")    #principal vectors/ eigen vectors
print(Vt)

pca_svd= np.matmul(X_scaled, Vt.transpose())
print("\n transformed data \n", pca_svd)       #transformed principal components

Shape of U: (10, 10)    S: (3,)    Vt (3, 3)
U: [[-0.12903036 -0.21839227  0.02025485 -0.11486499  0.01523355 -0.10749197
   0.42683596 -0.26415253  0.05492814 -0.80949526]
 [ 0.66669301  0.02174425  0.19999666  0.54703146  0.14989506 -0.39686657
   0.03199942  0.09473135  0.08301484 -0.13763891]
 [ 0.14638086 -0.10060633  0.09464466 -0.23565773  0.38826045  0.35442037
  -0.39344473  0.56546023  0.02839459 -0.39019043]
 [-0.51324075 -0.31491122  0.22138085  0.7147668   0.02147908  0.24432319
  -0.09351423  0.07964978 -0.02823629 -0.0383712 ]
 [-0.22137978  0.34314959  0.2064308  -0.02027774  0.82547525 -0.06306849
   0.16149905 -0.24337483 -0.02409298  0.13759994]
 [ 0.27162977  0.41840156 -0.270211    0.2652531  -0.0489155   0.71281627
   0.21997141 -0.18339279  0.03728132 -0.11778888]
 [ 0.19095172 -0.4144386   0.27083978 -0.14380081  0.06291575  0.2523406
   0.66563932  0.26795389 -0.04072629  0.33701252]
 [-0.29646094  0.54376056 -0.01319194  0.07910188 -0.17967015 -0.21550941
   0

Numpy result is same as my solution (computing eigen vectors of covariance matrix of normalized data). It is same because the eigen values are sorted as higher eigen value implies higher variance. The larger the absolute value of the coefficient, the more important the corresponding variable is in calculating the component. 

---



### (g) How many PCs are sufficient to represent the data in reduced dimensions with 95 % accuracy. Show how did you come up with you answer.

In [ ]:
print(pca.explained_variance_ratio_)

[0.58959138 0.30902531 0.10138332]


To represent the data in reduced dimensions with 95% accuracy, we will need 3 PCs as the largest 2 PCs can explain is 90% of the data so rest 10% can be represented after using the 3rd PC.

---

