In [3]:
import numpy as np              
from time import process_time                        #to calculate time
from tabulate import tabulate                        #to make table

my_table = []
for i in range(5,11):                                #looping for n= 5 to n=10      
  time_start = process_time()                        #starts noting the time   
  MatX = np.random.randint(8,size=(i,i))             #random matrix generated
  print(MatX)   
  detX = np.linalg.det(MatX)                      #checking for singular matrix
  
  if detX!=0:                                     #print detX
    invX=np.linalg.inv(MatX)                      #inverse of matrix calculated
    print(invX)
  else:
    print("Singular Matrix, no inverse found")
  time_stop = process_time()                      #time count stops
  net_time = time_stop-time_start                 #net = time stop - time start
  print("net time for n=%s = "%i ,net_time ,  "seconds")
  frobeniusnorm = np.linalg.norm(invX)
  entrydata= ("n= %s"%i, net_time, frobeniusnorm)           #for table purpose
  
  my_table.append(entrydata)                                #print entrydata

tableX = np.array(my_table)                                 #print tableX
                  

head = ["n" , "time" , "frobenius norm"]
XvsY = tabulate(tableX, headers = head, tablefmt="grid")
print(XvsY)


[[0 0 4 4 7]
 [7 7 4 2 7]
 [7 6 0 4 3]
 [1 1 0 3 7]
 [4 2 7 1 1]]
[[-0.59347699 -0.26674432  0.01688992  0.78276063  0.49155504]
 [ 0.54280722  0.37449039  0.04834013 -0.86313337 -0.52417006]
 [ 0.15666861  0.05765871 -0.04076878 -0.19976704  0.02038439]
 [ 0.32265579 -0.12288876  0.22830518 -0.2813046  -0.11415259]
 [-0.13104252  0.03727432 -0.10716366  0.27489808  0.05358183]]
net time for n=5 =  0.005333462000000289 seconds
[[7 2 0 0 3 2]
 [6 0 4 2 1 7]
 [2 6 0 0 2 7]
 [6 3 4 2 0 2]
 [3 2 7 3 4 3]
 [7 7 5 4 1 5]]
[[ 9.63431281e-02  2.16251167e-02 -4.04483081e-02  9.32538257e-02
  -5.30210504e-02 -1.76736835e-02]
 [-2.83066312e-02 -1.39090452e-01  1.07335297e-01  1.34420576e-01
   2.15532725e-03  7.18442417e-04]
 [-1.32983691e-01 -5.44579352e-02  1.18471155e-01  4.46224585e-01
   1.26876931e-01 -2.91041023e-01]
 [ 6.83957181e-02  1.27954594e-01 -3.45642647e-01 -8.07026367e-01
  -7.11976435e-02  6.42934119e-01]
 [ 1.60068970e-01 -4.08793735e-02 -2.32056901e-02 -2.62662548e-01
   1.400